name = "QuantileRegressions"
uuid = "c6596682-b856-542f-9fff-31404643e889"
version = "0.1.9"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"

[compat]
DataFrames = "0.18, 0.19, 0.20, 0.21, 0.22, 1.0"
Distributions = "0.20, 0.21, 0.22, 0.23, 0.24, 0.25"
StatsBase = "0.30, 0.31, 0.32, 0.33"
StatsModels = "0.6"
julia = "1.3"

[extras]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["CSV", "Test"]
